## Célula 1 — Instalação de dependências

Garante que todas as bibliotecas necessárias estão instaladas no ambiente.

In [56]:
# Execute esta célula apenas uma vez para instalar as dependências
# O '!' permite rodar comandos de terminal direto no Jupyter
#%pip install google-api-python-client isodate openpyxl python-dotenv requests --quiet

## Célula 2 — Imports

Carregamos todas as bibliotecas que serão usadas ao longo do notebook.

In [57]:
from __future__ import annotations

import os
import logging
from pathlib import Path
from datetime import datetime, timezone, timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, List

import isodate
import pandas as pd
import requests
from dotenv import load_dotenv
from googleapiclient.discovery import build

# ---------------------------------------------------------------------------
# Configuração de log
# Usamos logging ao invés de print() para ter controle de nível (INFO, WARNING, ERROR)
# Isso é especialmente útil em execuções longas: sabemos exatamente o que aconteceu
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

print("✅ Imports OK")

✅ Imports OK

## Célula 3 — Configuração via `.env`

### Por que `.env` e não hardcode?

A API Key **nunca** deve ficar no código-fonte.  
Se você versionar o projeto com Git, a chave ficaria exposta publicamente.  

Crie um arquivo `.env` na mesma pasta do notebook com o conteúdo:
```
YOUTUBE_API_KEY=sua_chave_aqui
```
O `python-dotenv` lê esse arquivo e injeta as variáveis no ambiente.

In [58]:
# Carrega as variáveis do arquivo .env para o ambiente
load_dotenv()

API_KEY: str = os.environ.get("YOUTUBE_API_KEY", "")

# Validação antecipada — melhor falhar cedo do que no meio da execução
if not API_KEY:
    raise EnvironmentError(
        "❌ Variável YOUTUBE_API_KEY não encontrada. "
        "Crie um arquivo .env com: YOUTUBE_API_KEY=sua_chave"
    )

print(f"✅ API Key carregada: {'*' * (len(API_KEY) - 4)}{API_KEY[-4:]}")

✅ API Key carregada: ***********************************6jF4

## Célula 4 — Parâmetros de execução

Centralizamos aqui tudo que o usuário pode querer ajustar.  
Isso evita que parâmetros fiquem espalhados pelo código.

In [59]:
# ──────────────────────────────────────────────
# Parâmetros — edite conforme sua necessidade
# ──────────────────────────────────────────────

CANAIS: List[str] = [
    "UC3Z2XdKUu21_KtMsohZedOQ", "UCN0W0kG9zolEDAn228CvFSQ", "UCCWSZHyZmONoOwb76uMkccg", "UCIRQQEextXQEV18j9kedBOw", "UC-ezuc6BSkMhdPIoaEU8S1g",
    "UCrNt1hZdMx-nFk-tqXsk-GQ", "UCnBNoed6NaPlpL8blj1yy8Q", "UCZE5espnlDl2dDRXD2XLMLg", "UCIt_jZw64ryRDpFW1w-m4vA", "UCcLvYJo2ke6Ckx4CqsEXyRQ",
    "UCkPwI3gaSr65levrx1j9okQ", "UCwLxXLLWEIJFHEeTMlYqHTA", "UCrp0zmecZ3TNV8FSR-tjv7A", "UCD_q9m3EPyFZZ0d3XWcrqWQ", "UCIeL1JF5Q7ALE1qOGPJBm5w",
    "UCj3jEZuLmXOndQJFkPTp3Nw", "UCBX4Z7RAs8ktgsyXm4ES_dg", "UC5Fl2W965fyBCv4gLb-U2hg", "UC_g73GNqsyBWvEehY0lNZBA", "UCD89tNSy9kC6QBjFAcgVd3g",
    "UC-hA65Fjv5X8h-J92zc_L8Q", "UCzLAzI6Q-0WX2IbKfLmtZUw", "UCfMKycqfaMdj9-jVDUuU15Q", "UCn_3RiYrABm3o7puJjTZO3w", "UCGnqRqH9I2v-rNdmXmHmHeg",
    "UChBtPExX9RjCdmpAizK7ccQ", "UC6pkw1C4ha1cmU9aDJ8OxUw", "UCRekFQ2mNTWbMwvH7JdD3xA", "UCQlVe5fDZN99GuRnBKzwn4w", "UCOn6-uNuXeXJqmbywtfBgdQ",
    "UCS4ZSVzsXgDiXV7Pwro4a0A", "UClmrZELCfAbZNzpl6rAT0gw", "UCHGl5Nn0GfMETBgjIkJDWjw", "UCD_q9m3EPyFZZ0d3XWcrqWQ", "UCteJrv6W7MWB5SoRvfjF36Q",
    "UCnTTl5-22qOKRSVmuGwm1Lw", "UCHniugO-y89ZBnaJUCn57Iw", "UCSXdP8V4jRaw-8YMTpa6glw", "UCN0W0kG9zolEDAn228CvFSQ", "UCiuihFCo8gfLInRK55F914g",
    "UCPUb-aMI0HiBjC1rsuRN4ng", "UC3XQ0w18WsYV3vf5E6E7D0w", "UCKjV2NaruwIaBORr9MCcAdw", "UCWTXUWC88wp6Xzr5fTpGEBQ","UCT3iQIbLMQc_wsj87KwlZWA", 
    "UCT0asn_SCNkzi1UDqPRBvUg", "UCUAqQbPNrc2rXx1LRWl5Q2A", "UCCE-jo1GvBJqyj1b287h7jA"
]

JANELA_DIAS: int = 30           # busca vídeos publicados nos últimos N dias
LIMITE_SHORTS_SEG: int = 180    # candidatos a Short para checar via redirecionamento (Shorts vão até ~3min)
MAX_WORKERS: int = 8            # threads simultâneas para buscar vídeos / verificar Shorts
SAIDA_XLSX: Path = Path("saida/videos_apenas.xlsx")  # caminho de saída

print(f"✅ {len(CANAIS)} canal(is) configurado(s)")
print(f"   Janela de busca       : últimos {JANELA_DIAS} dias")
print(f"   Limite p/ checar Short: <= {LIMITE_SHORTS_SEG}s")
print(f"   Workers (paralelo)    : {MAX_WORKERS}")
print(f"   Saída                 : {SAIDA_XLSX}")

✅ 48 canal(is) configurado(s)
   Janela de busca       : últimos 30 dias
   Limite p/ checar Short: <= 180s
   Workers (paralelo)    : 8
   Saída                 : saida\videos_apenas.xlsx

## Célula 5 — Cliente da YouTube Data API

### Melhoria: instanciar o cliente UMA única vez

Na versão original, `build()` era chamado dentro da função `duracoes_por_video_id()`.  
Isso significa que toda vez que a função fosse chamada, um novo cliente HTTP seria criado.

Aqui criamos o cliente **uma vez** e passamos ele como argumento — mais eficiente e testável.

In [60]:
# Criamos o cliente da API aqui, fora das funções
# Ele será reutilizado em todas as chamadas subsequentes
yt_client = build("youtube", "v3", developerKey=API_KEY)

print("✅ Cliente da YouTube Data API criado com sucesso")

11:47:32  INFO      file_cache is only supported with oauth2client<4.0.0

✅ Cliente da YouTube Data API criado com sucesso

## Célula 6 — Função: buscar vídeos de UM canal via playlist de uploads

### Por que não usar mais o RSS?

O feed RSS do YouTube sempre retorna no máximo os **15 vídeos mais recentes**
de um canal, sem possibilidade de paginar. Para canais muito ativos
(vários vídeos por dia), esses 15 itens podem cobrir bem menos que
`JANELA_DIAS` dias — vídeos mais antigos simplesmente nunca são vistos
pelo pipeline.

A `playlistItems.list` da YouTube Data API resolve isso: ela pagina
(50 itens por página, custo de 1 unidade de cota por página) sobre a
**playlist de uploads** do canal. Buscamos página a página até encontrar
um vídeo publicado antes da `data_corte` (ou a playlist acabar).

In [61]:
def _buscar_videos_playlist(
    cliente,
    playlist_id: str,
    channel_id: str,
    channel_title: str,
    data_corte: datetime,
) -> List[Dict]:
    """
    Busca vídeos de UMA playlist de uploads, paginando via playlistItems.list,
    até encontrar um item publicado antes de `data_corte` (ou a playlist acabar).

    Separamos em função própria para que o ThreadPoolExecutor
    possa chamá-la em paralelo para múltiplos canais.

    Retorna uma lista de dicionários com metadados básicos.
    Em caso de erro na API, retorna um item com o campo 'error' preenchido.
    """
    itens: List[Dict] = []
    page_token = None

    while True:
        try:
            resp = (
                cliente.playlistItems()
                .list(
                    part="snippet,contentDetails",
                    playlistId=playlist_id,
                    maxResults=50,
                    pageToken=page_token,
                )
                .execute()
            )
        except Exception as exc:  # noqa: BLE001
            log.error("Erro ao buscar playlist do canal %s: %s", channel_id, exc)
            return [{
                "channel_id": channel_id,
                "channel_title": channel_title,
                "video_id": None,
                "video_title": None,
                "video_url": None,
                "published": None,
                "error": str(exc),
            }]

        parar = False
        for item in resp.get("items", []):
            snippet = item.get("snippet", {})
            content = item.get("contentDetails", {})
            video_id = content.get("videoId")
            titulo = snippet.get("title")

            # Itens removidos/privados não têm dados úteis — pulamos
            if not video_id or titulo in ("Private video", "Deleted video"):
                continue

            # videoPublishedAt é a data real de publicação do vídeo
            # (mais confiável que snippet.publishedAt, que é a data em
            # que o vídeo entrou na playlist de uploads)
            published_str = content.get("videoPublishedAt") or snippet.get("publishedAt")
            if not published_str:
                continue

            published = datetime.fromisoformat(published_str.replace("Z", "+00:00"))

            if published < data_corte:
                parar = True
                break

            itens.append({
                "channel_id": channel_id,
                "channel_title": channel_title,
                "video_id": video_id,
                "video_title": titulo,
                "video_url": f"https://www.youtube.com/watch?v={video_id}",
                "published": published.isoformat(),
                "error": None,
            })

        page_token = resp.get("nextPageToken")
        if parar or not page_token:
            break

    log.info("Canal '%s' → %d vídeo(s) encontrado(s)", channel_title or channel_id, len(itens))
    return itens


print("✅ Função _buscar_videos_playlist definida")

✅ Função _buscar_videos_playlist definida

## Célula 7 — Função: buscar vídeos de TODOS os canais em paralelo

Para cada canal, criamos uma tarefa que busca os vídeos da playlist de uploads
(via `_buscar_videos_playlist`) a partir de uma `data_corte` calculada com
`JANELA_DIAS`.

As tarefas rodam em paralelo com `ThreadPoolExecutor`. Como os clientes
gerados por `googleapiclient.discovery.build()` **não são thread-safe**,
cada tarefa cria seu próprio cliente da API (`build("youtube", "v3", ...)`)
ao invés de compartilhar o `yt_client` global.

In [62]:
def buscar_videos_todos_canais(
    canais_info: List[Dict],
    janela_dias: int = 30,
    max_workers: int = 8,
) -> List[Dict]:
    """
    Busca vídeos de TODOS os canais em paralelo usando threads.

    Cada item de `canais_info` deve ser um dict com:
    - 'channel_id'
    - 'channel_title'
    - 'uploads_playlist_id'

    Por que threads e não multiprocessing?
    - A operação é I/O bound (espera de rede), não CPU bound
    - Threads são suficientes e mais leves para esse caso
    - O GIL do Python não é problema aqui

    Por que cada tarefa cria seu próprio cliente da API?
    - Objetos retornados por googleapiclient.discovery.build() não são
      thread-safe — compartilhar um único cliente entre threads pode
      causar erros intermitentes.

    Retorna lista com todos os vídeos de todos os canais.
    """
    data_corte = datetime.now(timezone.utc) - timedelta(days=janela_dias)
    todos: List[Dict] = []

    log.info(
        "Iniciando busca de vídeos para %d canal(is) com %d workers (últimos %d dias)...",
        len(canais_info), max_workers, janela_dias,
    )

    def _tarefa(info: Dict) -> List[Dict]:
        # Cada thread cria seu próprio cliente — não compartilhamos o yt_client global
        cliente_local = build("youtube", "v3", developerKey=API_KEY)
        return _buscar_videos_playlist(
            cliente_local,
            playlist_id=info["uploads_playlist_id"],
            channel_id=info["channel_id"],
            channel_title=info["channel_title"],
            data_corte=data_corte,
        )

    # submit() envia cada tarefa para o pool de threads
    # as_completed() itera sobre as futures à medida que terminam
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(_tarefa, info): info
            for info in canais_info
        }

        for future in as_completed(futures):
            info = futures[future]
            try:
                resultado = future.result()
                todos.extend(resultado)
            except Exception as exc:  # noqa: BLE001
                # Captura erros inesperados (timeout, etc.) sem derrubar tudo
                log.error("Falha inesperada no canal %s: %s", info["channel_id"], exc)
                todos.append({
                    "channel_id": info["channel_id"],
                    "channel_title": info.get("channel_title"),
                    "video_id": None,
                    "video_title": None,
                    "video_url": None,
                    "published": None,
                    "error": str(exc),
                })

    log.info("Total de itens coletados: %d", len(todos))
    return todos


print("✅ Função buscar_videos_todos_canais definida")

✅ Função buscar_videos_todos_canais definida

## Célula 8 — Função: buscar durações via YouTube Data API

### Melhorias aplicadas:
1. **Recebe o cliente** como parâmetro (não cria um novo a cada chamada)
2. **`try/except` por item**: um vídeo com dado faltando não interrompe o lote inteiro
3. **Log de progresso** para lotes grandes

In [63]:
def duracoes_por_video_id(
    cliente,
    video_ids: List[str],
) -> Dict[str, int]:
    """
    Retorna {video_id: duração_em_segundos} para todos os IDs informados.

    A YouTube Data API aceita no máximo 50 IDs por requisição,
    então processamos em lotes de 50.

    Parâmetros
    ----------
    cliente   : objeto retornado por googleapiclient.discovery.build()
    video_ids : lista de IDs de vídeos do YouTube
    """
    out: Dict[str, int] = {}
    total_lotes = (len(video_ids) + 49) // 50  # arredonda para cima

    for i in range(0, len(video_ids), 50):
        lote = video_ids[i : i + 50]
        num_lote = i // 50 + 1
        log.info("Buscando durações — lote %d/%d (%d vídeos)", num_lote, total_lotes, len(lote))

        try:
            resp = (
                cliente.videos()
                .list(part="contentDetails, statistics, liveStreamingDetails", id=",".join(lote))
                .execute()
            )
        except Exception as exc:  # noqa: BLE001
            # Erro na chamada HTTP do lote inteiro → loga e pula
            log.error("Erro na API para o lote %d: %s", num_lote, exc)
            continue

        for item in resp.get("items", []):
            vid = item["id"]
            try:
                # A duração vem no formato ISO 8601, ex: 'PT4M13S'
                # isodate.parse_duration converte para timedelta
                iso_dur = item["contentDetails"]["duration"]
                seconds = int(isodate.parse_duration(iso_dur).total_seconds())

                # ── Views ──────────────────────────────────────────────────
                # A API retorna viewCount como string — convertemos para int
                # get() com default '0' evita KeyError se o campo não existir
                # (acontece em alguns vídeos com métricas ocultas)
                view_count = int(item.get("statistics", {}).get("viewCount", 0))

                comment_count = int(item.get('statistics', {}).get('commentCount',0))

                # liveStreamingDetails só está presente em vídeos que foram
                # (ou são) transmissões ao vivo — ou seja, aparecem na aba
                # "Ao Vivo" do canal, não na aba "Vídeos"
                is_live_content = "liveStreamingDetails" in item

                out[vid] = {
                    "duration_seconds": seconds,
                    "view_count": view_count,
                    'comment_count': comment_count,
                    "is_live_content": is_live_content,
                }
                
            except (KeyError, AttributeError, ValueError) as exc:
                # Vídeo com dado malformado → registra aviso e continua
                log.warning("Não foi possível parsear duração de '%s': %s", vid, exc)

    log.info("Durações obtidas: %d/%d vídeos", len(out), len(video_ids))
    return out


print("✅ Função duracoes_por_video_id definida")

✅ Função duracoes_por_video_id definida

## Célula 9 — Função: filtrar Shorts

### Como identificamos Shorts

Desde 2024 o YouTube permite Shorts com até ~3 minutos de duração, então
duração sozinha (`<= 60s`) não é mais um critério confiável.

A verificação usada é a mesma que o próprio YouTube faz: ao acessar
`https://www.youtube.com/shorts/{video_id}`,
- se for um **Short**, a URL final permanece em `/shorts/...`
- se for um **vídeo normal**, o YouTube redireciona para `/watch?v=...`

Para evitar uma requisição extra para CADA vídeo, só checamos os
**candidatos**: vídeos com `duration_seconds <= LIMITE_SHORTS_SEG` (180s).
Vídeos mais longos que isso nunca são Shorts e pulam essa verificação.

In [64]:
def _eh_short_por_redirect(video_id: str) -> bool:
    """
    Verifica se um vídeo é Short checando o redirecionamento de
    https://www.youtube.com/shorts/{video_id}.

    - Se o YouTube redirecionar para /watch?v=..., NÃO é Short.
    - Se a URL final permanecer em /shorts/..., É Short.

    Em caso de erro de rede, assume que NÃO é Short — comportamento seguro
    para não descartar um vídeo válido por instabilidade de rede.
    """
    url = f"https://www.youtube.com/shorts/{video_id}"
    try:
        resp = requests.head(url, allow_redirects=True, timeout=10)
        return "/shorts/" in resp.url
    except requests.RequestException as exc:
        log.warning("Erro ao verificar Short de '%s': %s", video_id, exc)
        return False


def verificar_shorts_por_redirect(video_ids: List[str], max_workers: int = 8) -> Dict[str, bool]:
    """
    Verifica em paralelo, via redirecionamento, quais video_ids são Shorts.

    Retorna {video_id: is_short}.
    """
    out: Dict[str, bool] = {}
    if not video_ids:
        return out

    log.info("Verificando %d candidato(s) a Short via redirecionamento...", len(video_ids))

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(_eh_short_por_redirect, vid): vid
            for vid in video_ids
        }
        for future in as_completed(futures):
            vid = futures[future]
            try:
                out[vid] = future.result()
            except Exception as exc:  # noqa: BLE001
                log.error("Falha ao verificar Short de '%s': %s", vid, exc)
                out[vid] = False

    n_shorts = sum(out.values())
    log.info("Shorts identificados via redirecionamento: %d/%d candidato(s)", n_shorts, len(video_ids))
    return out


print("✅ Função verificar_shorts_por_redirect definida")

✅ Função verificar_shorts_por_redirect definida

In [65]:
def somente_videos_nao_shorts(
    df: pd.DataFrame,
    cliente,
    limite_shorts_seg: int = 180,
    max_workers: int = 8,
) -> pd.DataFrame:
    """
    Enriquece o DataFrame com a duração de cada vídeo, remove Shorts
    (via verificação de redirecionamento de /shorts/{id}) e remove
    transmissões ao vivo gravadas (aba "Ao Vivo" do canal).

    Como Shorts podem ter até ~3 minutos, só verificamos via redirecionamento
    os vídeos com duration_seconds <= limite_shorts_seg — vídeos mais longos
    nunca são Shorts e pulam essa checagem.

    Vídeos sem duração retornada pela API são DESCARTADOS
    (comportamento seguro: melhor perder um vídeo do que incluir um Short).
    """
    df = df.copy()

    ids = df["video_id"].dropna().astype(str).unique().tolist()
    if not ids:
        log.warning("Nenhum video_id válido encontrado — retornando DataFrame vazio.")
        return df

    log.info("%d video_id(s) únicos para consultar na API", len(ids))

    dados = duracoes_por_video_id(cliente, ids)
    df["duration_seconds"] = df["video_id"].map(
        {vid: v["duration_seconds"] for vid, v in dados.items()}
    )
    df["view_count"] = df["video_id"].map(
        {vid: v["view_count"] for vid, v in dados.items()}
    )

    df["comment_count"] = df["video_id"].map(
    {vid: v["comment_count"] for vid, v in dados.items()}
    )

    df["is_live_content"] = df["video_id"].map(
        {vid: v["is_live_content"] for vid, v in dados.items()}
    )

    # Remove vídeos sem duração confirmada (NaN) — comportamento seguro
    antes = len(df)
    df = df[df["duration_seconds"].notna()]
    removidos = antes - len(df)
    log.info("%d vídeo(s) sem duração confirmada removido(s). Restam %d vídeo(s).", removidos, len(df))

    # Candidatos a Short: duração <= limite_shorts_seg (Shorts vão até ~3min)
    candidatos = (
        df.loc[df["duration_seconds"] <= limite_shorts_seg, "video_id"]
        .dropna().unique().tolist()
    )
    shorts_map = verificar_shorts_por_redirect(candidatos, max_workers=max_workers)
    df["is_short"] = df["video_id"].map(shorts_map).fillna(False)

    antes = len(df)
    df = df[~df["is_short"]]
    removidos = antes - len(df)
    log.info("%d Short(s) removido(s) via redirecionamento. Restam %d vídeo(s).", removidos, len(df))

    # Remove transmissões ao vivo gravadas (presentes na aba "Ao Vivo", não em "Vídeos")
    antes_live = len(df)
    df = df[~df["is_live_content"].fillna(False)]
    removidos_live = antes_live - len(df)
    log.info("%d transmissão(ões) ao vivo gravada(s) removida(s). Restam %d vídeo(s).", removidos_live, len(df))

    return df


print("✅ Função somente_videos_nao_shorts definida")

✅ Função somente_videos_nao_shorts definida

## Célula 10 — Função: buscar metadados dos canais (inscritos + playlist de uploads)

Para cada canal, buscamos de uma vez (em lotes de 50):
- `channel_title` — nome do canal
- `subscriber_count` — número de inscritos
- `uploads_playlist_id` — ID da playlist de uploads, usado pela `_buscar_videos_playlist`

Usa `channels().list(part='snippet,statistics,contentDetails')`.

In [66]:
def buscar_info_canais(
    cliente,
    channel_ids: List[str],
) -> Dict[str, Dict]:
    """
    Retorna {channel_id: {"channel_title", "subscriber_count", "uploads_playlist_id"}}
    para todos os canais informados.

    Usa o endpoint channels().list(part='snippet,statistics,contentDetails')
    da YouTube Data API. O limite por requisição é de 50 IDs.

    Canais com contagem de inscritos oculta (hiddenSubscriberCount=True)
    retornam subscriber_count=0.

    Canais sem 'contentDetails.relatedPlaylists.uploads' (raro) retornam
    uploads_playlist_id=None — esses canais são ignorados na busca de vídeos.
    """
    out: Dict[str, Dict] = {}

    # Remove duplicatas — a lista de canais configurada pode ter repetidos
    ids_unicos = list(dict.fromkeys(channel_ids))
    total_lotes = (len(ids_unicos) + 49) // 50

    for i in range(0, len(ids_unicos), 50):
        lote = ids_unicos[i : i + 50]
        num_lote = i // 50 + 1
        log.info(
            "Buscando metadados dos canais — lote %d/%d (%d canais)",
            num_lote, total_lotes, len(lote),
        )

        try:
            resp = (
                cliente.channels()
                .list(part="snippet,statistics,contentDetails", id=",".join(lote))
                .execute()
            )
        except Exception as exc:
            log.error("Erro na API de canais, lote %d: %s", num_lote, exc)
            continue

        for item in resp.get("items", []):
            cid = item["id"]
            snippet = item.get("snippet", {})
            stats = item.get("statistics", {})
            content = item.get("contentDetails", {})

            # Canais podem ocultar o número de inscritos
            # Nesse caso, hiddenSubscriberCount é True e subscriberCount vem como '0'
            hidden = stats.get("hiddenSubscriberCount", False)
            if hidden:
                log.info("Canal %s oculta inscritos.", cid)

            uploads_playlist_id = (
                content.get("relatedPlaylists", {}).get("uploads")
            )
            if not uploads_playlist_id:
                log.warning("Canal %s sem playlist de uploads — será ignorado.", cid)

            out[cid] = {
                "channel_title": snippet.get("title"),
                "subscriber_count": int(stats.get("subscriberCount", 0)),
                "uploads_playlist_id": uploads_playlist_id,
            }

    log.info("Metadados obtidos: %d/%d canais", len(out), len(ids_unicos))
    return out


print("✅ Função buscar_info_canais definida")

✅ Função buscar_info_canais definida

## Célula 11 — Função: salvar Excel

Mantida praticamente igual à original — já estava bem implementada.  
Adicionamos apenas log de confirmação.

In [67]:
def salvar_excel(
    df: pd.DataFrame,
    path_xlsx: str | Path,
    sheet_name: str = "videos",
) -> None:
    """
    Salva o DataFrame em arquivo .xlsx.

    O Excel não aceita datas com timezone, então convertemos
    para UTC e depois removemos a informação de fuso.
    """
    path_xlsx = Path(path_xlsx)
    path_xlsx.parent.mkdir(parents=True, exist_ok=True)

    df = df.copy()
    
    # Percorre TODAS as colunas do tipo datetime e remove o timezone
    # Assim funciona independente do nome da coluna (published, Data de publicacao, etc.)
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = (
                pd.to_datetime(df[col], errors="coerce", utc=True)
                .dt.tz_convert(None)
            )

    with pd.ExcelWriter(path_xlsx, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name=sheet_name)

    log.info("✅ Arquivo salvo: %s  (%d linhas)", path_xlsx, len(df))


print("✅ Função salvar_excel definida")

✅ Função salvar_excel definida

## Célula 12 — Função: filtrar vídeos por data e palavras-chave no título

### O que esta função faz

Aplica três filtros em sequência sobre o DataFrame:

**Filtro A — Data (aplicado primeiro):**  
Remove todos os vídeos publicados há mais de `janela_dias` dias.  
Usamos `pd.Timestamp.now(tz='UTC')` para ter a data atual já em UTC,  
o mesmo fuso que o YouTube usa no campo `published`.

**Filtro B — Palavras-chave no título (lógica OU):**  
Mantém apenas vídeos cujo título contenha **pelo menos uma** das palavras-chave.  
Usamos `str.contains(..., case=False)` — isso torna a busca **case-insensitive**,  
ou seja, 'fiis', 'FIIS' e 'FIIs' são tratados da mesma forma.

**Filtro C — Mínimo de views (aplicado por último):**  
Remove vídeos com menos de `min_views` visualizações.  
Vídeos sem `view_count` (NaN) também são descartados — comportamento seguro.

### Bibliotecas utilizadas
- **`pandas`** — `.str.contains()`, comparação de datas e números, `pd.Timestamp`  
- **`datetime`** — `timedelta` para calcular o intervalo de dias  
Nenhuma biblioteca nova — tudo já importado.

In [68]:
def filtrar_por_data_e_titulo(
    df: pd.DataFrame,
    palavras_chave: List[str],
    janela_dias: int = 30,
    min_views: int = 1000,
) -> pd.DataFrame:
    """
    Filtra o DataFrame em duas etapas:

    1. Remove vídeos publicados há mais de `janela_dias` dias.
    2. Mantém apenas vídeos cujo título contenha pelo menos
       uma das `palavras_chave` (busca case-insensitive).
    3. Remove vídeos com menos de `min_views` visualizações.

    Parâmetros
    ----------
    df            : DataFrame com colunas 'published', 'video_title' e 'view_count'
    palavras_chave: lista de termos a buscar no título (ex: ['fiis', 'gare11'])
    janela_dias   : quantos dias para trás considerar a partir de hoje
    min_views     : número mínimo de visualizações (inclusive)
    """
    df = df.copy()

    # ── Etapa 1: Filtro de data ────────────────────────────────────────────
    #
    # Convertemos a coluna 'published' para datetime com UTC
    # (o YouTube sempre publica em UTC — precisamos garantir que estamos
    #  comparando datas no mesmo fuso para não eliminar vídeos errados)
    #
    df["published"] = pd.to_datetime(df["published"], errors="coerce", utc=True)

    # Data de corte: hoje (UTC) menos janela_dias
    from datetime import timedelta
    data_corte = pd.Timestamp.now(tz="UTC") - timedelta(days=janela_dias)

    antes_data = len(df)
    # Mantemos apenas vídeos MAIS RECENTES que a data de corte
    # Vídeos sem data (NaT) são descartados — comportamento seguro
    df = df[df["published"] >= data_corte]
    removidos_data = antes_data - len(df)

    log.info(
        "Filtro de data (últimos %d dias): %d removido(s), %d restante(s)",
        janela_dias, removidos_data, len(df),
    )

    if df.empty:
        log.warning("Nenhum vídeo nos últimos %d dias.", janela_dias)
        return df

    # ── Etapa 2: Filtro de palavras-chave no título (lógica OU) ────────────
    #
    # Para cada palavra-chave, criamos uma máscara booleana (True/False por linha)
    # usando str.contains com case=False (ignora maiúsculas/minúsculas)
    # e na=False (trata título NaN como False, não levanta erro)
    #
    # Em seguida combinamos todas as máscaras com OR (|)
    # Resultado: True se o título contiver QUALQUER uma das palavras
    #
    mascara_titulo = pd.Series(False, index=df.index)  # começa tudo False

    for palavra in palavras_chave:
        mascara_titulo = mascara_titulo | df["video_title"].str.contains(
            palavra, case=False, na=False
        )

    antes_titulo = len(df)
    df = df[mascara_titulo]
    removidos_titulo = antes_titulo - len(df)

    log.info(
        "Filtro de título %s: %d removido(s), %d restante(s)",
        palavras_chave, removidos_titulo, len(df),
    )
    if df.empty:
        log.warning("Nenhum vídeo passou pelo filtro de título.")
        return df

    # ── Etapa 3: Filtro de views mínimas ──────────────────────────────────
    #
    # view_count >= min_views mantém o vídeo
    # NaN (vídeo sem dado de views) é descartado — comportamento seguro
    #
    antes_views = len(df)
    df = df[df["view_count"] >= min_views]
    removidos_views = antes_views - len(df)

    log.info(
        "Filtro de views (>= %d): %d removido(s), %d restante(s)",
        min_views, removidos_views, len(df),
    )

    return df


print("✅ Função filtrar_por_data_e_titulo definida")

✅ Função filtrar_por_data_e_titulo definida

## Célula 13 — Execução principal

Aqui orquestramos tudo na sequência correta, com logs intermediários para acompanhamento.

```
Passo 0 → Buscar metadados dos canais (inscritos + playlist de uploads)
Passo 1 → Buscar vídeos via playlist de uploads (paralelo, paginado)
Passo 2 → Remove Shorts e transmissões ao vivo (API)
Passo 3 → Filtra por data e palavras-chave no título
Passo 4 → Organiza colunas e exporta para Excel
```

In [69]:
# ── Passo 0: buscar metadados dos canais (inscritos + playlist de uploads) ─
info_canais = buscar_info_canais(yt_client, CANAIS)

# Monta a lista de canais válidos (com playlist de uploads) para a busca de vídeos
canais_info = [
    {
        "channel_id": cid,
        "channel_title": info["channel_title"],
        "uploads_playlist_id": info["uploads_playlist_id"],
    }
    for cid, info in info_canais.items()
    if info["uploads_playlist_id"] is not None
]

print(f"\n{len(canais_info)}/{len(info_canais)} canal(is) com playlist de uploads válida")

# ── Passo 1: buscar vídeos via playlist de uploads (em paralelo) ───────────
itens = buscar_videos_todos_canais(
    canais_info=canais_info,
    janela_dias=JANELA_DIAS,
    max_workers=MAX_WORKERS,
)

df = pd.DataFrame(itens)
print(f"\nDataFrame inicial: {len(df)} linha(s)")
df.head()

11:47:32  INFO      Buscando metadados dos canais — lote 1/1 (46 canais)
11:47:33  INFO      Metadados obtidos: 46/46 canais
11:47:33  INFO      Iniciando busca de vídeos para 46 canal(is) com 8 workers (últimos 30 dias)...
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:33  INFO      file_cache is only supported with oauth2client<4.0.0

46/46 canal(is) com playlist de uploads válida

11:47:34  INFO      Canal 'EconoMirna' → 0 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Bruno Perini - Você MAIS Rico' → 20 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'kelly investe' → 0 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Renda Com Dividendos | Lucas Santos' → 46 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Ramos de Dinheiro' → 11 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Ela Investe' → 11 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Ricardo Amorim' → 18 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:34  INFO      Canal 'Dicionário do Investidor' → 102 vídeo(s) encontrado(s)
11:47:34  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Pequeno investidor' → 20 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Investir e CRESCER' → 5 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Dinheiro Com Você - Por William Ribeiro' → 20 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Mestre da Riqueza' → 36 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Investidor Classe Media' → 25 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Stella Mourão FIIs' → 33 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:35  INFO      Canal 'Se Banque!' → 8 vídeo(s) encontrado(s)
11:47:35  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Riqueza Em Dias' → 11 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'FONTE DA FORTUNA - Alexandre Winkler' → 19 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Lucas Fii - Fundos Imobiliários' → 168 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Geração Dividendos' → 23 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Alex Fiis' → 20 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Liberdade Financeira com Fiis' → 27 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Clube do Valor' → 51 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:36  INFO      Canal 'Irmãos Dias Podcast' → 63 vídeo(s) encontrado(s)
11:47:36  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Felipe Almeida - Seu Dividendo' → 3 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Dia a Dia Investindo' → 2 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Eitonilda' → 3 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Professor Baroni | Fundos Imobiliários (FIIs)' → 100 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Lucro FC' → 16 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Rob Correa Research' → 0 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Liberdade é Logo Ali - Eric Leonardo' → 63 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  INFO      Canal 'Academia Thomaz Xavier de Finanças' → 17 vídeo(s) encontrado(s)
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:37  ERROR     Erro ao buscar playlist do canal UCRekFQ2mNTWbMwvH7JdD3xA: <HttpError 404 when requesting https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet%2CcontentDetails&playlistId=UURekFQ2mNTWbMwvH7JdD3xA&maxResults=50&key=AIzaSyCPlnOVpG6pU2Or39gXtOZMD3SAezR6jF4&alt=json returned "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.". Details: "[{'message': "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.", 'domain': 'youtube.playlistItem', 'reason': 'playlistNotFound', 'location': 'playlistId', 'locationType': 'parameter'}]">
11:47:37  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Financeologia' → 12 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Gêmeos Investem' → 38 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Matheus Campos | Efeito Investimentos' → 0 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Breno Perrucho - Jovens de Negócios' → 2 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Dani Mengue' → 4 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'Economista Sincero' → 90 vídeo(s) encontrado(s)
11:47:38  INFO      file_cache is only supported with oauth2client<4.0.0
11:47:38  INFO      Canal 'TioFiis | Mateus Lima' → 54 vídeo(s) encontrado(s)
11:47:38  INFO      Canal 'ClickInvest' → 7 vídeo(s) encontrado(s)
11:47:39  INFO      Canal 'Academia de Fundos Imobiliários ' → 3 vídeo(s) encontrado(s)
11:47:39  INFO      Canal 'Hannah Guarilha Investimentos' → 11 vídeo(s) encontrado(s)
11:47:39  INFO      Canal 'ONEBERTO - Fundos Imobiliários' → 0 vídeo(s) encontrado(s)
11:47:39  INFO      Canal 'A Cara da Riqueza' → 35 vídeo(s) encontrado(s)
11:47:39  INFO      Canal 'FIIs com Neto Pereira' → 0 vídeo(s) encontrado(s)
11:47:41  INFO      Canal 'TubaCast | Tubarão da Bolsa' → 317 vídeo(s) encontrado(s)
11:47:41  INFO      Total de itens coletados: 1515

DataFrame inicial: 1515 linha(s)

,channel_id,channel_title,video_id,video_title,video_url,published,error
0,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,LjfCA1GkVAY,OS PRINCÍPIOS DE INVESTIMENTOS DO BARSI #shorts,https://www.youtube.com/watch?v=LjfCA1GkVAY,2026-06-10T22:00:26+00:00,None
1,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,bChOoRDJEHc,O PLANO MAIS REALISTA PARA CHEGAR AO PRIMEIRO ...,https://www.youtube.com/watch?v=bChOoRDJEHc,2026-06-09T22:00:04+00:00,None
2,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,-P1y-jgkA5g,UM TERÇO DA RENDA DO BRASILEIRO VAI PARA PARA ...,https://www.youtube.com/watch?v=-P1y-jgkA5g,2026-06-08T22:00:15+00:00,None
3,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,vLcUkhZUkIc,COMO A DÉCADA DE 80 DESTRUIU A CLASSE MÉDIA BR...,https://www.youtube.com/watch?v=vLcUkhZUkIc,2026-06-07T22:00:11+00:00,None
4,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,6ZuCAQ1TZW8,O QUE É SER CLASSE MÉDIA NO BRASIL? #shorts,https://www.youtube.com/watch?v=6ZuCAQ1TZW8,2026-06-06T22:00:18+00:00,None

In [70]:
# ── Passo 2: filtrar Shorts e transmissões ao vivo (YouTube Data API) ──────
df = somente_videos_nao_shorts(
    df,
    cliente=yt_client,
    limite_shorts_seg=LIMITE_SHORTS_SEG,
    max_workers=MAX_WORKERS,
)

print(f"\nDataFrame após filtro de Shorts/lives: {len(df)} linha(s)")

# Mapeia o subscriber_count para cada linha usando o channel_id
# (já obtido no Passo 0, junto com a playlist de uploads)
df["subscriber_count"] = df["channel_id"].map(
    {cid: info["subscriber_count"] for cid, info in info_canais.items()}
)

print(f"\nInscritos mapeados para {df['subscriber_count'].notna().sum()} vídeo(s)")
df.head()

11:47:41  INFO      1514 video_id(s) únicos para consultar na API
11:47:41  INFO      Buscando durações — lote 1/31 (50 vídeos)
11:47:41  INFO      Buscando durações — lote 2/31 (50 vídeos)
11:47:42  INFO      Buscando durações — lote 3/31 (50 vídeos)
11:47:42  INFO      Buscando durações — lote 4/31 (50 vídeos)
11:47:42  INFO      Buscando durações — lote 5/31 (50 vídeos)
11:47:42  INFO      Buscando durações — lote 6/31 (50 vídeos)
11:47:42  INFO      Buscando durações — lote 7/31 (50 vídeos)
11:47:43  INFO      Buscando durações — lote 8/31 (50 vídeos)
11:47:43  INFO      Buscando durações — lote 9/31 (50 vídeos)
11:47:43  INFO      Buscando durações — lote 10/31 (50 vídeos)
11:47:43  INFO      Buscando durações — lote 11/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 12/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 13/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 14/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 15/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 16/31 (50 vídeos)
11:47:44  INFO      Buscando durações — lote 17/31 (50 vídeos)
11:47:45  INFO      Buscando durações — lote 18/31 (50 vídeos)
11:47:45  INFO      Buscando durações — lote 19/31 (50 vídeos)
11:47:45  INFO      Buscando durações — lote 20/31 (50 vídeos)
11:47:45  INFO      Buscando durações — lote 21/31 (50 vídeos)
11:47:46  INFO      Buscando durações — lote 22/31 (50 vídeos)
11:47:46  INFO      Buscando durações — lote 23/31 (50 vídeos)
11:47:46  INFO      Buscando durações — lote 24/31 (50 vídeos)
11:47:46  INFO      Buscando durações — lote 25/31 (50 vídeos)
11:47:46  INFO      Buscando durações — lote 26/31 (50 vídeos)
11:47:47  INFO      Buscando durações — lote 27/31 (50 vídeos)
11:47:47  INFO      Buscando durações — lote 28/31 (50 vídeos)
11:47:47  INFO      Buscando durações — lote 29/31 (50 vídeos)
11:47:47  INFO      Buscando durações — lote 30/31 (50 vídeos)
11:47:47  INFO      Buscando durações — lote 31/31 (14 vídeos)
11:47:48  INFO      Durações obtidas: 1514/1514 vídeos
11:47:48  INFO      1 vídeo(s) sem duração confirmada removido(s). Restam 1514 vídeo(s).
11:47:48  INFO      Verificando 608 candidato(s) a Short via redirecionamento...
11:49:26  INFO      Shorts identificados via redirecionamento: 584/608 candidato(s)
C:\Users\LucasCavalcante\AppData\Local\Temp\ipykernel_35516\157523742.py:56: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["is_short"] = df["video_id"].map(shorts_map).fillna(False)
11:49:26  INFO      584 Short(s) removido(s) via redirecionamento. Restam 930 vídeo(s).
C:\Users\LucasCavalcante\AppData\Local\Temp\ipykernel_35516\157523742.py:65: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df[~df["is_live_content"].fillna(False)]
11:49:26  INFO      85 transmissão(ões) ao vivo gravada(s) removida(s). Restam 845 vídeo(s).

DataFrame após filtro de Shorts/lives: 845 linha(s)

Inscritos mapeados para 845 vídeo(s)

,channel_id,channel_title,video_id,video_title,video_url,published,error,duration_seconds,view_count,comment_count,is_live_content,is_short,subscriber_count
1,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,bChOoRDJEHc,O PLANO MAIS REALISTA PARA CHEGAR AO PRIMEIRO ...,https://www.youtube.com/watch?v=bChOoRDJEHc,2026-06-09T22:00:04+00:00,None,1353.0,41594.0,91.0,False,False,2070000
6,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,qCBWQuhl1T4,LUIZ BARSI: A FILOSOFIA DE VIDA E INVESTIMENTO...,https://www.youtube.com/watch?v=qCBWQuhl1T4,2026-06-03T23:02:50+00:00,None,2731.0,93734.0,279.0,False,False,2070000
8,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,1OU6VyiS12A,AINDA É CEDO PARA COMPRAR BITCOIN? (comparei o...,https://www.youtube.com/watch?v=1OU6VyiS12A,2026-05-28T22:12:35+00:00,None,1262.0,111168.0,202.0,False,False,2070000
9,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,Gud0ZoHL0ZE,A MAIORIA DAS PESSOAS ENTENDE DIVIDENDOS DO JE...,https://www.youtube.com/watch?v=Gud0ZoHL0ZE,2026-05-25T23:00:14+00:00,None,1269.0,51770.0,107.0,False,False,2070000
10,UCCE-jo1GvBJqyj1b287h7jA,Bruno Perini - Você MAIS Rico,MpxTvSsApo0,COMO GANHAR DINHEIRO ONLINE? | A estratégia ma...,https://www.youtube.com/watch?v=MpxTvSsApo0,2026-05-21T22:20:36+00:00,None,806.0,38272.0,21.0,False,False,2070000

In [71]:
# ── Passo 3: filtrar por data e palavras-chave no título ───────────────────
#
# PALAVRAS_CHAVE funciona com lógica OU:
# o vídeo permanece se o título contiver QUALQUER uma das palavras listadas.
# A busca ignora maiúsculas/minúsculas automaticamente.
#
PALAVRAS_CHAVE: List[str] = ["gare11"]

df = filtrar_por_data_e_titulo(
    df,
    palavras_chave=PALAVRAS_CHAVE,
    janela_dias=JANELA_DIAS,
)

print(f"\nDataFrame após filtro de data e título: {len(df)} linha(s)")
df.head()

11:49:26  INFO      Filtro de data (últimos 30 dias): 1 removido(s), 844 restante(s)
11:49:26  INFO      Filtro de título ['gare11']: 824 removido(s), 20 restante(s)
11:49:26  INFO      Filtro de views (>= 1000): 0 removido(s), 20 restante(s)

DataFrame após filtro de data e título: 20 linha(s)

,channel_id,channel_title,video_id,video_title,video_url,published,error,duration_seconds,view_count,comment_count,is_live_content,is_short,subscriber_count
63,UC-ezuc6BSkMhdPIoaEU8S1g,Renda Com Dividendos | Lucas Santos,NMMYqTXqYA0,GARE11 como você conhecia ACABOU e quase NINGU...,https://www.youtube.com/watch?v=NMMYqTXqYA0,2026-05-14 21:03:48+00:00,None,961.0,17937.0,125.0,False,False,256000
148,UCcLvYJo2ke6Ckx4CqsEXyRQ,Dicionário do Investidor,6w358l1OymE,Proventos de Junho: FIIs de Tijolos - HGLG11 K...,https://www.youtube.com/watch?v=6w358l1OymE,2026-05-29 23:45:02+00:00,None,1401.0,3102.0,25.0,False,False,82100
223,UCHniugO-y89ZBnaJUCn57Iw,Pequeno investidor,cXz7bHcHPuA,GARE11: Chegou a HORA DE COMPRAR? análise comp...,https://www.youtube.com/watch?v=cXz7bHcHPuA,2026-05-19 15:26:49+00:00,None,751.0,3881.0,20.0,False,False,18400
225,UCHniugO-y89ZBnaJUCn57Iw,Pequeno investidor,RffuRBtoO0g,"GARE11, TRXF11 e GGRC11: 3 RISCOS QUE VOCÊ NÃO...",https://www.youtube.com/watch?v=RffuRBtoO0g,2026-05-15 11:15:44+00:00,None,694.0,1953.0,12.0,False,False,18400
272,UCteJrv6W7MWB5SoRvfjF36Q,Mestre da Riqueza,QRJw7hF-6f4,GARE11 TEM UM PROBLEMÃO À VISTA? Análise Completa,https://www.youtube.com/watch?v=QRJw7hF-6f4,2026-05-24 11:00:34+00:00,None,1551.0,32761.0,76.0,False,False,319000

In [72]:
# ── Passo 4: organizar colunas e exportar ──────────────────────────────────
COLUNAS_FINAIS = [
    "channel_title",
    "subscriber_count",
    "published",
    "duration_seconds",
    "view_count",
    "comment_count",
    "video_title",
    "video_url",
    "video_id",
    "channel_id",
    "error",
]

# Filtramos apenas as colunas que existem no DataFrame
# (evita KeyError se alguma coluna não foi gerada)
df = df[[c for c in COLUNAS_FINAIS if c in df.columns]]

df = df.rename(columns={
    "channel_title"   : "Nome do Canal",
    "subscriber_count": "Inscritos",
    "published"       : "Data de publicacao",
    "duration_seconds": "Duracao",
    "view_count"      : "Views",
    "comment_count"   : "Comentarios",
    "video_title"     : "Titulo do video",
    "video_url"       : "Url do video",
    "video_id"        : "Id video",
    "channel_id"      : "Id Canal",
})

salvar_excel(df, SAIDA_XLSX)

print("\n✅ Pipeline concluído com sucesso!")
df

11:49:26  INFO      ✅ Arquivo salvo: saida\videos_apenas.xlsx  (20 linhas)

✅ Pipeline concluído com sucesso!

,Nome do Canal,Inscritos,Data de publicacao,Duracao,Views,Comentarios,Titulo do video,Url do video,Id video,Id Canal,error
63,Renda Com Dividendos | Lucas Santos,256000,2026-05-14 21:03:48+00:00,961.0,17937.0,125.0,GARE11 como você conhecia ACABOU e quase NINGU...,https://www.youtube.com/watch?v=NMMYqTXqYA0,NMMYqTXqYA0,UC-ezuc6BSkMhdPIoaEU8S1g,None
148,Dicionário do Investidor,82100,2026-05-29 23:45:02+00:00,1401.0,3102.0,25.0,Proventos de Junho: FIIs de Tijolos - HGLG11 K...,https://www.youtube.com/watch?v=6w358l1OymE,6w358l1OymE,UCcLvYJo2ke6Ckx4CqsEXyRQ,None
223,Pequeno investidor,18400,2026-05-19 15:26:49+00:00,751.0,3881.0,20.0,GARE11: Chegou a HORA DE COMPRAR? análise comp...,https://www.youtube.com/watch?v=cXz7bHcHPuA,cXz7bHcHPuA,UCHniugO-y89ZBnaJUCn57Iw,None
225,Pequeno investidor,18400,2026-05-15 11:15:44+00:00,694.0,1953.0,12.0,"GARE11, TRXF11 e GGRC11: 3 RISCOS QUE VOCÊ NÃO...",https://www.youtube.com/watch?v=RffuRBtoO0g,RffuRBtoO0g,UCHniugO-y89ZBnaJUCn57Iw,None
272,Mestre da Riqueza,319000,2026-05-24 11:00:34+00:00,1551.0,32761.0,76.0,GARE11 TEM UM PROBLEMÃO À VISTA? Análise Completa,https://www.youtube.com/watch?v=QRJw7hF-6f4,QRJw7hF-6f4,UCteJrv6W7MWB5SoRvfjF36Q,None
303,Investidor Classe Media,18200,2026-05-24 11:02:04+00:00,647.0,1440.0,28.0,GARE11 é COMPRA OU ARMADILHA? Entenda ISSO Ant...,https://www.youtube.com/watch?v=wkjLh5SGGmM,wkjLh5SGGmM,UCn_3RiYrABm3o7puJjTZO3w,None
335,Stella Mourão FIIs,29400,2026-05-22 15:00:35+00:00,824.0,2808.0,18.0,#HGLG11 - VENDA DE GARE11 NO PREJUÍZO (DE NOVO)!,https://www.youtube.com/watch?v=nNQaREH3Vuw,nNQaREH3Vuw,UCWTXUWC88wp6Xzr5fTpGEBQ,None
343,Stella Mourão FIIs,29400,2026-05-15 15:00:13+00:00,663.0,4049.0,33.0,#GARE11 - A XP NÃO COMEÇOU A VENDER!,https://www.youtube.com/watch?v=AR739dbQZJo,AR739dbQZJo,UCWTXUWC88wp6Xzr5fTpGEBQ,None
356,Riqueza Em Dias,438000,2026-05-30 19:59:11+00:00,1442.0,9775.0,71.0,NÃO COMPRE TRXF11 ou GARE11 ANTES DE VER ISSO!,https://www.youtube.com/watch?v=ix83RJmbi_4,ix83RJmbi_4,UCPUb-aMI0HiBjC1rsuRN4ng,None
361,Riqueza Em Dias,438000,2026-05-19 22:51:54+00:00,976.0,13110.0,174.0,O GARE11 NÃO é mais o mesmo fundo e VOCÊ NÃO p...,https://www.youtube.com/watch?v=7hAsNjIq20s,7hAsNjIq20s,UCPUb-aMI0HiBjC1rsuRN4ng,None
376,FONTE DA FORTUNA - Alexandre Winkler,1080000,2026-05-26 21:30:07+00:00,1504.0,46318.0,335.0,NÃO COMPRE TRXF11 ou GARE11 ANTES DE VER ESSE ...,https://www.youtube.com/watch?v=Q6Xh2WEuo_Q,Q6Xh2WEuo_Q,UCD89tNSy9kC6QBjFAcgVd3g,None
579,Alex Fiis,11800,2026-06-05 20:45:03+00:00,502.0,1695.0,13.0,"GARE11, EXPECTATIVAS DE DIVIDENDOS, RISCOS, SI...",https://www.youtube.com/watch?v=B1_Lf78ySc0,B1_Lf78ySc0,UCIRQQEextXQEV18j9kedBOw,None
601,Liberdade Financeira com Fiis,63800,2026-06-04 20:00:23+00:00,801.0,4298.0,41.0,GARE11: Cadê os 6 Imóveis? A Compra Está Demor...,https://www.youtube.com/watch?v=nxvn0VtFzZY,nxvn0VtFzZY,UCS4ZSVzsXgDiXV7Pwro4a0A,None
606,Liberdade Financeira com Fiis,63800,2026-05-29 22:40:10+00:00,602.0,3962.0,26.0,MXRF11 HGBS11 VGHF11 GARE11 TRXF11 ANÚNCIO DE ...,https://www.youtube.com/watch?v=ppoC3KSiKRU,ppoC3KSiKRU,UCS4ZSVzsXgDiXV7Pwro4a0A,None
696,Irmãos Dias Podcast,1190000,2026-06-01 12:00:01+00:00,894.0,45769.0,138.0,ESSES FIIs são OPORTUNIDADE ou CILADA? (GARE11...,https://www.youtube.com/watch?v=M_3Ns2hbLYI,M_3Ns2hbLYI,UChBtPExX9RjCdmpAizK7ccQ,None
862,Liberdade é Logo Ali - Eric Leonardo,42200,2026-06-10 15:00:32+00:00,645.0,1542.0,13.0,#GARE11 - ALOCAÇÃO DOS RECURSOS DA 7ª EMISSÃO ...,https://www.youtube.com/watch?v=U8btSC_36_U,U8btSC_36_U,UCOn6-uNuXeXJqmbywtfBgdQ,None
921,Liberdade é Logo Ali - Eric Leonardo,42200,2026-05-13 15:01:11+00:00,473.0,1815.0,25.0,"#GARE11 - FUNDO SEGUE SEM NOVIDADES, AGUARDAND...",https://www.youtube.com/watch?v=irucLKM0c1E,irucLKM0c1E,UCOn6-uNuXeXJqmbywtfBgdQ,None
1111,TioFiis | Mateus Lima,115000,2026-05-27 20:00:33+00:00,869.0,25427.0,147.0,URGENTE: TRXF11 E GARE11 EM RISCO? GRUPO MATEU...,https://www.youtube.com/watch?v=NS6esXFeUWY,NS6esXFeUWY,UCT0asn_SCNkzi1UDqPRBvUg,None
1162,Hannah Guarilha Investimentos,30100,2026-05-15 19:30:24+00:00,1391.0,11434.0,471.0,GARE11 - Virou FOF? Cota caindo e número de co...,https://www.youtube.com/watch?v=xLQZUzFjiEM,xLQZUzFjiEM,UCfMKycqfaMdj9-jVDUuU15Q,None
1186,A Cara da Riqueza,1150000,2026-05-20 21:05:43+00:00,1061.0,91956.0,290.0,COMO RECEBER R$300 POR MÊS COM O GARE11 E KNSC...,https://www.youtube.com/watch?v=OVGvwiDKqsU,OVGvwiDKqsU,UC3Z2XdKUu21_KtMsohZedOQ,None